#! /bin/bash
pushd "${0%/*}" >/dev/null

export COMPlus_TieredCompilation=1
# export COMPlus_gcServer=1
export COMPlus_gcConcurrent=1
export COMPlus_GCLatencyLevel=0
# export COMPlus_GCLatencyMode=1
export COMPlus_GCCpuGroup=1
export COMPlus_Thread_UseAllCpuGroups=1
export COMPlus_GCRetainVM=1

dotnet run -p App/GCBurn.App.csproj -c Release -- $@

popd >/dev/null
